on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          set -x
          cat /proc/sys/kernel/core_pattern || :
          sudo sh -c 'echo "core.%e-%i-%t" > /proc/sys/kernel/core_pattern' || :
          cat /proc/sys/kernel/core_pattern || :
          ulimit -c || :
          ulimit -c unlimited
          sleep 60 &
          kill -11 $!
          find . -name 'core.*' || :
